# Generated by Django 2.1.5 on 2019-01-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageType', models.CharField(choices=[('PP', 'Pools Page'), ('TP', 'Team Page'), ('ET', 'Event Team Page')], max_length=2)),
                ('url', models.URLField()),
            ],
        ),
    ]
