# Generated by Django 2.1.5 on 2019-01-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_poolpageteaminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolpageteaminfo',
            name='seed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scraperquery',
            name='pageType',
            field=models.CharField(choices=[('PP', 'Pools Page'), ('TP', 'Team Page'), ('ET', 'Event Team Page')], help_text='Select your page type', max_length=2, verbose_name='Page Type'),
        ),
        migrations.AlterField(
            model_name='scraperquery',
            name='url',
            field=models.URLField(help_text='Link to a USA Ultimate page', verbose_name='URL'),
        ),
    ]
