# Generated by Django 2.1.5 on 2019-01-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20190121_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolpageteaminfo',
            name='poolSeed',
            field=models.IntegerField(default=0),
        ),
    ]
