# Generated by Django 2.1.5 on 2019-02-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraper', '0006_poolpageteaminfo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolpageteaminfo',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.ScraperQuery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scraperquery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
