# Generated by Django 2.1.5 on 2019-02-07 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20190207_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperquery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
