# Generated by Django 2.1.5 on 2019-02-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_20190207_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraperquery',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='poolpageteaminfo',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
