# Generated by Django 2.1.5 on 2019-02-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_teampagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampagedata',
            name='nickname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
