# Generated by Django 2.1.5 on 2019-02-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_teampagedata_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperquery',
            name='division',
            field=models.CharField(choices=[('O', 'Open'), ('X', 'Mixed'), ('W', 'Womens'), ('CO', 'College Open'), ('CW', 'College Womens'), ('YO', 'Youth Open'), ('YX', 'Youth Mixed'), ('YW', 'Youth Womens')], default='CO', help_text='Select the division for this page', max_length=2, verbose_name='Division'),
            preserve_default=False,
        ),
    ]
