# Generated by Django 2.1.5 on 2019-02-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_scraperquery_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperquery',
            name='tournament',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
