# Generated by Django 2.1.2 on 2018-10-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='anders.juengst@gmail.com', help_text='email to contact user', max_length=200, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
    ]
