# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_twitterlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='twitterHandle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
