# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20180828_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='team0_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team1_score',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='games',
        ),
        migrations.AlterField(
            model_name='rostermembership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Player'),
        ),
        migrations.AlterField(
            model_name='rostermembership',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Roster'),
        ),
        migrations.AddField(
            model_name='gamemembership',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Game'),
        ),
        migrations.AddField(
            model_name='gamemembership',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Roster'),
        ),
        migrations.AddField(
            model_name='game',
            name='rosters',
            field=models.ManyToManyField(through='teams.GameMembership', to='teams.Roster'),
        ),
    ]
