# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-04 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20180830_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
