# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20180904_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='team',
            new_name='associated_team',
        ),
        migrations.AddField(
            model_name='team',
            name='rosters',
            field=models.ManyToManyField(to='teams.Roster'),
        ),
    ]
