# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20180905_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterCoachMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('H', 'Head'), ('A', 'Assistant')], max_length=20)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Person')),
            ],
        ),
        
        migrations.AlterField(
            model_name='roster',
            name='players',
            field=models.ManyToManyField(related_name='playsOn', through='teams.RosterMembership', to='teams.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='year',
            field=models.IntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='team',
            name='rosters',
            field=models.ManyToManyField(blank=True, to='teams.Roster'),
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.AddField(
            model_name='rostercoachmembership',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Roster'),
        ),
        migrations.AddField(
            model_name='roster',
            name='coaches',
            field=models.ManyToManyField(related_name='coaches', through='teams.RosterCoachMembership', to='teams.Person'),
        ),
    ]
