# Generated by Django 2.1.5 on 2019-02-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_team_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
